import forge._C.graph
from typing import overload

class AutogradConfig:
    def __init__(self, recompute: bool = ..., optimizer: object = ...) -> None: ...

class AutogradContext:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def constant(self, arg0: int) -> forge._C.graph.NodeContext: ...
    @overload
    def constant(self, arg0: float) -> forge._C.graph.NodeContext: ...
    def create_optimizer_op(self, type: str, operands: list[forge._C.graph.NodeContext], attributes=...) -> forge._C.graph.NodeContext: ...
    def get_operands(self, arg0: forge._C.graph.NodeContext) -> list[forge._C.graph.NodeContext]: ...
    def get_pytorch_tensor(self, arg0: forge._C.graph.NodeContext) -> object: ...
    def get_shape(self, arg0: forge._C.graph.NodeContext) -> list[int]: ...
    def input(self, *args, **kwargs): ...
    def loopback(self, arg0: forge._C.graph.NodeContext, arg1: forge._C.graph.NodeContext) -> None: ...
    def op(self, type: str | object, operands: list[forge._C.graph.NodeContext], attributes=...) -> forge._C.graph.NodeContext: ...
    def tensor(self, arg0: object) -> forge._C.graph.NodeContext: ...

class AutogradEngine:
    def __init__(self, arg0: forge._C.graph.Graph, arg1: AutogradConfig) -> None: ...
    def run(self) -> forge._C.graph.Graph: ...
