FROM ghcr.io/tenstorrent/tt-forge-fe/tt-forge-fe-base-ubuntu-22-04:latest AS slimci
SHELL ["/bin/bash", "-c"]

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Copy requirements
COPY env/core_requirements.txt /tmp/core_requirements.txt

# Install python packages for compiler/core only
RUN pip install --upgrade pip setuptools wheel && \
    pip install --ignore-installed -r /tmp/core_requirements.txt
