// SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0
#include "ops/python_bindings.hpp"

#include <pybind11/operators.h>
#include <pybind11/stl.h>

#include "ops/op.hpp"

namespace tt
{

void OpsModule(py::module &m_ops)
{
    py::enum_<ops::OpType>(m_ops, "OpType")
        .value("Abs", ops::OpType::Abs)
        .value("AdaptiveMaxPool2d", ops::OpType::AdaptiveMaxPool2d)
        .value("Add", ops::OpType::Add)
        .value("AdvIndex", ops::OpType::AdvIndex)
        .value("Argmax", ops::OpType::Argmax)
        .value("Atan", ops::OpType::Atan)
        .value("AvgPool1d", ops::OpType::AvgPool1d)
        .value("AvgPool2d", ops::OpType::AvgPool2d)
        .value("Batchnorm", ops::OpType::Batchnorm)
        .value("Broadcast", ops::OpType::Broadcast)
        .value("Cast", ops::OpType::Cast)
        .value("Clip", ops::OpType::Clip)
        .value("Concatenate", ops::OpType::Concatenate)
        .value("Constant", ops::OpType::Constant)
        .value("Conv2d", ops::OpType::Conv2d)
        .value("Conv2dDepthwiseWeights", ops::OpType::Conv2dDepthwiseWeights)
        .value("Conv2dDepthwiseWeightsBw", ops::OpType::Conv2dDepthwiseWeightsBw)
        .value("Conv2dGroupedWeights", ops::OpType::Conv2dGroupedWeights)
        .value("Conv2dGroupedWeightsBw", ops::OpType::Conv2dGroupedWeightsBw)
        .value("Conv2dPrestrideAct", ops::OpType::Conv2dPrestrideAct)
        .value("Conv2dPrestrideWeights", ops::OpType::Conv2dPrestrideWeights)
        .value("Conv2dTranspose", ops::OpType::Conv2dTranspose)
        .value("Conv3d", ops::OpType::Conv3d)
        .value("ConvSum", ops::OpType::ConvSum)
        .value("Cosine", ops::OpType::Cosine)
        .value("CumulativeSum", ops::OpType::CumulativeSum)
        .value("Depthwise", ops::OpType::Depthwise)
        .value("Divide", ops::OpType::Divide)
        .value("Downsample2d", ops::OpType::Downsample2d)
        .value("Dropout", ops::OpType::Dropout)
        .value("Embedding", ops::OpType::Embedding)
        .value("EmbeddingBw", ops::OpType::EmbeddingBw)
        .value("Equal", ops::OpType::Equal)
        .value("Erf", ops::OpType::Erf)
        .value("Exp", ops::OpType::Exp)
        .value("FillCache", ops::OpType::FillCache)
        .value("ForgePad", ops::OpType::ForgePad)
        .value("ForgeUnpad", ops::OpType::ForgeUnpad)
        .value("Gelu", ops::OpType::Gelu)
        .value("Greater", ops::OpType::Greater)
        .value("GreaterEqual", ops::OpType::GreaterEqual)
        .value("Heaviside", ops::OpType::Heaviside)
        .value("Hstack", ops::OpType::Hstack)
        .value("Index", ops::OpType::Index)
        .value("IndexCopy", ops::OpType::IndexCopy)
        .value("Interleave", ops::OpType::Interleave)
        .value("Layernorm", ops::OpType::Layernorm)
        .value("LayernormBw", ops::OpType::LayernormBw)
        .value("LeakyRelu", ops::OpType::LeakyRelu)
        .value("Less", ops::OpType::Less)
        .value("LessEqual", ops::OpType::LessEqual)
        .value("Log", ops::OpType::Log)
        .value("LogSoftmax", ops::OpType::LogSoftmax)
        .value("LogicalAnd", ops::OpType::LogicalAnd)
        .value("LogicalNot", ops::OpType::LogicalNot)
        .value("Mask", ops::OpType::Mask)
        .value("Matmul", ops::OpType::Matmul)
        .value("MaxPool1d", ops::OpType::MaxPool1d)
        .value("MaxPool2d", ops::OpType::MaxPool2d)
        .value("Maximum", ops::OpType::Maximum)
        .value("Minimum", ops::OpType::Minimum)
        .value("Multiply", ops::OpType::Multiply)
        .value("Nop", ops::OpType::Nop)
        .value("NotEqual", ops::OpType::NotEqual)
        .value("Pad", ops::OpType::Pad)
        .value("PadTile", ops::OpType::PadTile)
        .value("PixelShuffle", ops::OpType::PixelShuffle)
        .value("Pow", ops::OpType::Pow)
        .value("Power", ops::OpType::Power)
        .value("Reciprocal", ops::OpType::Reciprocal)
        .value("ReduceAvg", ops::OpType::ReduceAvg)
        .value("ReduceMax", ops::OpType::ReduceMax)
        .value("ReduceSum", ops::OpType::ReduceSum)
        .value("Relu", ops::OpType::Relu)
        .value("Remainder", ops::OpType::Remainder)
        .value("Repeat", ops::OpType::Repeat)
        .value("RepeatInterleave", ops::OpType::RepeatInterleave)
        .value("Reshape", ops::OpType::Reshape)
        .value("Resize2d", ops::OpType::Resize2d)
        .value("Select", ops::OpType::Select)
        .value("Sigmoid", ops::OpType::Sigmoid)
        .value("Sine", ops::OpType::Sine)
        .value("Softmax", ops::OpType::Softmax)
        .value("SoftmaxBw", ops::OpType::SoftmaxBw)
        .value("Sqrt", ops::OpType::Sqrt)
        .value("Stack", ops::OpType::Stack)
        .value("Subtract", ops::OpType::Subtract)
        .value("Squeeze", ops::OpType::Squeeze)
        .value("Tanh", ops::OpType::Tanh)
        .value("Transpose", ops::OpType::Transpose)
        .value("Unsqueeze", ops::OpType::Unsqueeze)
        .value("UpdateCache", ops::OpType::UpdateCache)
        .value("Upsample2d", ops::OpType::Upsample2d)
        .value("Vstack", ops::OpType::Vstack)
        .value("Where", ops::OpType::Where)
        .export_values();
}

}  // namespace tt
