# SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC

# SPDX-License-Identifier: Apache-2.0

# Script to update license headers in autogenerated stub files (.pyi)
import os
import datetime

def get_license_header():
    year = datetime.date.today().year
    return f"""# SPDX-FileCopyrightText: © {year} Tenstorrent AI ULC

# SPDX-License-Identifier: Apache-2.0

"""

def update_spdx_pyi(file_path, license_header):
    with open(file_path, "r") as f:
        content = f.read()

    with open(file_path, "w") as f:
        f.write(license_header + content)

license_header = get_license_header()
for root, _, files in os.walk("."):
    for file in files:
        if file.endswith(".pyi"):
            file_path = os.path.join(root, file)
            update_spdx_pyi(file_path, license_header)

