# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
import forge
import forge.op
from forge import ForgeModule

from loguru import logger
import torch

from forge import Tensor, compile
from forge.verify.compare import compare_with_golden
from forge.verify.verify import verify
from forge.verify.config import VerifyConfig
import pytest


class Sqrt0(ForgeModule):
    def __init__(self, name):
        super().__init__(name)

    def forward(self, sqrt_input_0):
        sqrt_output_1 = forge.op.Sqrt("", sqrt_input_0)
        return sqrt_output_1


def ids_func(param):
    forge_module, shapes_dtypes, _ = param
    return str(forge_module.__name__) + "-" + str(shapes_dtypes)


forge_modules_and_shapes_dtypes_list = [
    (
        Sqrt0,
        [((2, 13, 1), torch.float32)],
        {"model_name": ["pt_musicgen_large", "pt_musicgen_small", "pt_musicgen_medium"]},
    ),
    (Sqrt0, [((1, 7, 1), torch.float32)], {"model_name": ["pt_gemma_2b"]}),
    (
        Sqrt0,
        [((1, 256, 1), torch.float32)],
        {
            "model_name": [
                "pt_Llama_3_1_8B_Instruct_causal_lm",
                "pt_Meta_Llama_3_8B_causal_lm",
                "pt_Llama_3_2_1B_Instruct_causal_lm",
                "pt_Meta_Llama_3_8B_Instruct_causal_lm",
                "pt_Llama_3_2_1B_causal_lm",
                "pt_Llama_3_1_8B_causal_lm",
            ]
        },
    ),
    (
        Sqrt0,
        [((1, 4, 1), torch.float32)],
        {
            "model_name": [
                "pt_Llama_3_1_8B_Instruct_seq_cls",
                "pt_Meta_Llama_3_8B_seq_cls",
                "pt_Llama_3_2_1B_Instruct_seq_cls",
                "pt_Llama_3_2_1B_seq_cls",
                "pt_Llama_3_1_8B_seq_cls",
                "pt_Meta_Llama_3_8B_Instruct_seq_cls",
            ]
        },
    ),
    (Sqrt0, [((1, 128, 1), torch.float32)], {"model_name": ["pt_Mistral_7B_v0_1"]}),
    (
        Sqrt0,
        [((1, 29, 1), torch.float32)],
        {
            "model_name": [
                "pt_qwen_chat",
                "pt_Qwen_Qwen2_5_1_5B",
                "pt_Qwen_Qwen2_5_7B",
                "pt_Qwen_Qwen2_5_0_5B",
                "pt_Qwen_Qwen2_5_3B",
            ]
        },
    ),
    (Sqrt0, [((1, 6, 1), torch.float32)], {"model_name": ["pt_qwen_causal_lm"]}),
    (
        Sqrt0,
        [((1, 35, 1), torch.float32)],
        {
            "model_name": [
                "pt_Qwen_Qwen2_5_Coder_1_5B_Instruct",
                "pt_Qwen_Qwen2_5_Coder_3B",
                "pt_Qwen_Qwen2_5_Coder_7B",
                "pt_Qwen_Qwen2_5_Coder_1_5B",
                "pt_Qwen_Qwen2_5_Coder_0_5B",
                "pt_Qwen_Qwen2_5_Coder_3B_Instruct",
                "pt_Qwen_Qwen2_5_Coder_7B_Instruct",
            ]
        },
    ),
    (
        Sqrt0,
        [((1, 39, 1), torch.float32)],
        {
            "model_name": [
                "pt_Qwen_Qwen2_5_1_5B_Instruct",
                "pt_Qwen_Qwen2_5_0_5B_Instruct",
                "pt_Qwen_Qwen2_5_3B_Instruct",
                "pt_Qwen_Qwen2_5_7B_Instruct",
            ]
        },
    ),
    (
        Sqrt0,
        [((1, 1, 1), torch.float32)],
        {
            "model_name": [
                "pt_t5_large",
                "pt_t5_base",
                "pt_google_flan_t5_base",
                "pt_t5_small",
                "pt_google_flan_t5_small",
            ]
        },
    ),
    (
        Sqrt0,
        [((64,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_dla169",
                "pt_dla60",
                "pt_dla46_c",
                "pt_dla46x_c",
                "pt_dla102",
                "pt_dla34",
                "pt_dla60x_c",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_224",
                "pt_mobilenet_v1_basic",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
                "pt_monodle",
                "pt_vision_perceiver_conv",
                "pt_resnet50_timm",
                "pt_resnet50",
                "pt_resnext50_torchhub",
                "pt_resnext101_torchhub",
                "pt_resnext14_osmr",
                "pt_resnext26_osmr",
                "pt_resnext101_fb_wsl",
                "pt_resnext101_osmr",
                "pt_resnext50_osmr",
                "pt_retinanet_rn18fpn",
                "pt_retinanet_rn152fpn",
                "pt_retinanet_rn101fpn",
                "pt_retinanet_rn50fpn",
                "pt_retinanet_rn34fpn",
                "pt_ssd300_resnet50",
                "pt_unet_cityscapes_osmr",
                "pt_unet_qubvel_pt",
                "pt_unet_torchhub",
                "pt_bn_vgg19_osmr",
                "pt_bn_vgg19b_osmr",
                "pt_vgg_bn19_torchhub",
                "pt_vgg19_bn_timm",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet27s",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_wide_resnet101_2_timm",
                "pt_wide_resnet50_2_hub",
                "pt_wide_resnet50_2_timm",
                "pt_wide_resnet101_2_hub",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
                "pt_yolox_s",
                "pt_yolox_darknet",
                "pt_yolox_nano",
                "pt_yolox_l",
            ]
        },
    ),
    (
        Sqrt0,
        [((128,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_dla102x",
                "pt_dla169",
                "pt_dla60",
                "pt_dla46_c",
                "pt_dla102x2",
                "pt_dla46x_c",
                "pt_dla60x",
                "pt_dla102",
                "pt_dla34",
                "pt_dla60x_c",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_224",
                "pt_mobilenet_v1_basic",
                "pt_monodle",
                "pt_regnet_y_040",
                "pt_resnet50_timm",
                "pt_resnet50",
                "pt_resnext50_torchhub",
                "pt_resnext14_osmr",
                "pt_resnext26_osmr",
                "pt_resnext50_osmr",
                "pt_retinanet_rn18fpn",
                "pt_retinanet_rn152fpn",
                "pt_retinanet_rn101fpn",
                "pt_retinanet_rn50fpn",
                "pt_retinanet_rn34fpn",
                "pt_ssd300_resnet50",
                "pt_unet_cityscapes_osmr",
                "pt_unet_qubvel_pt",
                "pt_unet_torchhub",
                "pt_bn_vgg19_osmr",
                "pt_bn_vgg19b_osmr",
                "pt_vgg_bn19_torchhub",
                "pt_vgg19_bn_timm",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet27s",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_wide_resnet101_2_timm",
                "pt_wide_resnet50_2_hub",
                "pt_wide_resnet50_2_timm",
                "pt_wide_resnet101_2_hub",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
                "pt_yolox_s",
                "pt_yolox_darknet",
                "pt_yolox_nano",
                "pt_yolox_l",
            ]
        },
    ),
    (
        Sqrt0,
        [((96,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_192",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_160",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_small",
                "pt_mobilenetv3_small_100",
                "pt_vovnet27s",
                "pt_yolox_m",
                "pt_yolox_tiny",
            ]
        },
    ),
    (
        Sqrt0,
        [((160,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_ghostnet_100",
                "pt_googlenet",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w40",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_yolox_x",
            ]
        },
    ),
    (
        Sqrt0,
        [((192,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_192",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_regnet_y_040",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_yolox_m",
                "pt_yolox_tiny",
            ]
        },
    ),
    (
        Sqrt0,
        [((224,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_googlenet",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
            ]
        },
    ),
    (
        Sqrt0,
        [((256,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_dla102x",
                "pt_dla169",
                "pt_dla60",
                "pt_dla46_c",
                "pt_dla102x2",
                "pt_dla46x_c",
                "pt_dla60x",
                "pt_dla102",
                "pt_dla34",
                "pt_dla60x_c",
                "pt_fpn",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_224",
                "pt_mobilenet_v1_basic",
                "mobilenetv2_deeplabv3",
                "pt_monodle",
                "pt_resnet50_timm",
                "pt_resnet50",
                "pt_resnext50_torchhub",
                "pt_resnext101_torchhub",
                "pt_resnext14_osmr",
                "pt_resnext26_osmr",
                "pt_resnext101_fb_wsl",
                "pt_resnext101_osmr",
                "pt_resnext50_osmr",
                "pt_retinanet_rn18fpn",
                "pt_retinanet_rn152fpn",
                "pt_retinanet_rn101fpn",
                "pt_retinanet_rn50fpn",
                "pt_retinanet_rn34fpn",
                "pt_segformer_b0_finetuned_ade_512_512",
                "pt_segformer_b1_finetuned_ade_512_512",
                "pt_ssd300_resnet50",
                "pt_unet_cityscapes_osmr",
                "pt_unet_qubvel_pt",
                "pt_unet_torchhub",
                "pt_bn_vgg19_osmr",
                "pt_bn_vgg19b_osmr",
                "pt_vgg_bn19_torchhub",
                "pt_vgg19_bn_timm",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet27s",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_wide_resnet101_2_timm",
                "pt_wide_resnet50_2_hub",
                "pt_wide_resnet50_2_timm",
                "pt_wide_resnet101_2_hub",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
                "pt_yolox_s",
                "pt_yolox_darknet",
                "pt_yolox_nano",
                "pt_yolox_l",
            ]
        },
    ),
    (
        Sqrt0,
        [((288,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_googlenet",
                "mobilenetv2_160",
                "pt_mobilenet_v3_small",
                "pt_mobilenetv3_small_100",
            ]
        },
    ),
    (
        Sqrt0,
        [((320,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_googlenet",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w40",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_yolox_x",
            ]
        },
    ),
    (
        Sqrt0,
        [((352,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_osmr_hrnetv2_w44",
            ]
        },
    ),
    (
        Sqrt0,
        [((384,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_192",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_vovnet27s",
                "pt_yolox_m",
                "pt_yolox_tiny",
            ]
        },
    ),
    (Sqrt0, [((416,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((448,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
            ]
        },
    ),
    (
        Sqrt0,
        [((480,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (
        Sqrt0,
        [((512,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_dla102x",
                "pt_dla169",
                "pt_dla60",
                "pt_dla102x2",
                "pt_dla60x",
                "pt_dla102",
                "pt_dla34",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_224",
                "pt_mobilenet_v1_basic",
                "pt_monodle",
                "pt_regnet_y_040",
                "pt_resnet50_timm",
                "pt_resnet50",
                "pt_resnext50_torchhub",
                "pt_resnext101_torchhub",
                "pt_resnext14_osmr",
                "pt_resnext26_osmr",
                "pt_resnext101_fb_wsl",
                "pt_resnext101_osmr",
                "pt_resnext50_osmr",
                "pt_retinanet_rn18fpn",
                "pt_retinanet_rn152fpn",
                "pt_retinanet_rn101fpn",
                "pt_retinanet_rn50fpn",
                "pt_retinanet_rn34fpn",
                "pt_ssd300_resnet50",
                "pt_unet_cityscapes_osmr",
                "pt_unet_qubvel_pt",
                "pt_unet_torchhub",
                "pt_bn_vgg19_osmr",
                "pt_bn_vgg19b_osmr",
                "pt_vgg_bn19_torchhub",
                "pt_vgg19_bn_timm",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet27s",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_wide_resnet101_2_timm",
                "pt_wide_resnet50_2_hub",
                "pt_wide_resnet50_2_timm",
                "pt_wide_resnet101_2_hub",
                "pt_yolox_s",
                "pt_yolox_darknet",
                "pt_yolox_l",
            ]
        },
    ),
    (Sqrt0, [((544,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((576,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_small",
                "pt_mobilenetv3_small_100",
            ]
        },
    ),
    (Sqrt0, [((608,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((640,), torch.float32)],
        {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201", "pt_yolox_x"]},
    ),
    (
        Sqrt0,
        [((672,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (Sqrt0, [((704,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((736,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((768,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_mobilenet_v1_192",
                "pt_segformer_b4_finetuned_ade_512_512",
                "pt_segformer_b2_finetuned_ade_512_512",
                "pt_segformer_b3_finetuned_ade_512_512",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_yolox_m",
            ]
        },
    ),
    (Sqrt0, [((800,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((832,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((864,), torch.float32)],
        {"model_name": ["pt_densenet121", "pt_densenet_161", "pt_densenet_169", "pt_densenet_201"]},
    ),
    (Sqrt0, [((896,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((928,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((960,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_ghostnet_100",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (Sqrt0, [((992,), torch.float32)], {"model_name": ["pt_densenet121", "pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((1024,), torch.float32)],
        {
            "model_name": [
                "pt_densenet121",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_dla102x",
                "pt_dla169",
                "pt_dla60",
                "pt_dla102x2",
                "pt_dla60x",
                "pt_dla102",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_mobilenet_v1_224",
                "pt_mobilenet_v1_basic",
                "pt_resnet50_timm",
                "pt_resnet50",
                "pt_resnext50_torchhub",
                "pt_resnext101_torchhub",
                "pt_resnext14_osmr",
                "pt_resnext26_osmr",
                "pt_resnext101_fb_wsl",
                "pt_resnext101_osmr",
                "pt_resnext50_osmr",
                "pt_retinanet_rn152fpn",
                "pt_retinanet_rn101fpn",
                "pt_retinanet_rn50fpn",
                "pt_ssd300_resnet50",
                "pt_unet_qubvel_pt",
                "pt_ese_vovnet19b_dw",
                "pt_ese_vovnet39b",
                "pt_vovnet39",
                "vovnet_57_stigma_pt",
                "pt_ese_vovnet99b",
                "pt_vovnet_39_stigma",
                "pt_vovnet57",
                "pt_wide_resnet101_2_timm",
                "pt_wide_resnet50_2_hub",
                "pt_wide_resnet50_2_timm",
                "pt_wide_resnet101_2_hub",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
                "pt_yolox_darknet",
                "pt_yolox_l",
            ]
        },
    ),
    (
        Sqrt0,
        [((144,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_161",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_160",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_small",
                "pt_mobilenetv3_small_100",
            ]
        },
    ),
    (
        Sqrt0,
        [((240,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_161",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_osmr_hrnetv2_w30",
                "mobilenetv2_160",
                "pt_mobilenet_v3_small",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_small_100",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (
        Sqrt0,
        [((336,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_161",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_ghostnet_100",
                "mobilenetv2_96",
            ]
        },
    ),
    (Sqrt0, [((432,), torch.float32)], {"model_name": ["pt_densenet_161", "mobilenetv2_160"]}),
    (Sqrt0, [((528,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((624,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((720,), torch.float32)], {"model_name": ["pt_densenet_161", "mobilenetv2_160"]}),
    (Sqrt0, [((816,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((912,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1008,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1056,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1104,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (
        Sqrt0,
        [((1152,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
            ]
        },
    ),
    (Sqrt0, [((1200,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1248,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1296,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1344,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1392,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1440,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1488,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (
        Sqrt0,
        [((1536,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
            ]
        },
    ),
    (Sqrt0, [((1584,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (
        Sqrt0,
        [((1632,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_161",
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
            ]
        },
    ),
    (Sqrt0, [((1680,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1728,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_201"]}),
    (Sqrt0, [((1776,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1824,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_201"]}),
    (Sqrt0, [((1872,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1920,), torch.float32)], {"model_name": ["pt_densenet_161", "pt_densenet_201"]}),
    (Sqrt0, [((1968,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((2016,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((2064,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((2112,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((2160,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((2208,), torch.float32)], {"model_name": ["pt_densenet_161"]}),
    (Sqrt0, [((1088,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201", "pt_regnet_y_040"]}),
    (Sqrt0, [((1120,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1184,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1216,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (
        Sqrt0,
        [((1280,), torch.float32)],
        {
            "model_name": [
                "pt_densenet_169",
                "pt_densenet_201",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "mobilenetv2_basic",
                "mobilenetv2_160",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_yolox_x",
            ]
        },
    ),
    (Sqrt0, [((1312,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1376,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1408,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1472,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1504,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1568,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1600,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1664,), torch.float32)], {"model_name": ["pt_densenet_169", "pt_densenet_201"]}),
    (Sqrt0, [((1696,), torch.float32)], {"model_name": ["pt_densenet_201"]}),
    (Sqrt0, [((1760,), torch.float32)], {"model_name": ["pt_densenet_201"]}),
    (
        Sqrt0,
        [((1792,), torch.float32)],
        {"model_name": ["pt_densenet_201", "pt_efficientnet_b4_timm", "pt_efficientnet_b4_torchvision"]},
    ),
    (Sqrt0, [((1856,), torch.float32)], {"model_name": ["pt_densenet_201"]}),
    (Sqrt0, [((1888,), torch.float32)], {"model_name": ["pt_densenet_201"]}),
    (
        Sqrt0,
        [((16,), torch.float32)],
        {
            "model_name": [
                "pt_dla102x",
                "pt_dla169",
                "pt_dla60",
                "pt_dla46_c",
                "pt_dla102x2",
                "pt_dla46x_c",
                "pt_dla60x",
                "pt_dla102",
                "pt_dla34",
                "pt_dla60x_c",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_160",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_small",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_small_100",
                "pt_mobilenetv3_large_100",
                "pt_monodle",
                "pt_unet_qubvel_pt",
                "pt_yolox_nano",
            ]
        },
    ),
    (
        Sqrt0,
        [((32,), torch.float32)],
        {
            "model_name": [
                "pt_dla102x",
                "pt_dla169",
                "pt_dla60",
                "pt_dla46_c",
                "pt_dla102x2",
                "pt_dla46x_c",
                "pt_dla60x",
                "pt_dla102",
                "pt_dla34",
                "pt_dla60x_c",
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_timm_inception_v4",
                "pt_osmr_inception_v4",
                "pt_mobilenet_v1_224",
                "pt_mobilenet_v1_basic",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_monodle",
                "pt_regnet_y_040",
                "pt_unet_qubvel_pt",
                "pt_unet_torchhub",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
                "pt_yolox_s",
                "pt_yolox_darknet",
                "pt_yolox_nano",
            ]
        },
    ),
    (
        Sqrt0,
        [((2048,), torch.float32)],
        {
            "model_name": [
                "pt_dla102x2",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w64",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_timm_hrnet_w32",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_osmr_hrnetv2_w32",
                "pt_hrnet_timm_hrnet_w40",
                "pt_hrnet_osmr_hrnetv2_w30",
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_timm_hrnet_w18_small",
                "pt_hrnet_timm_hrnet_w64",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_hrnet_osmr_hrnet_w18_small_v1",
                "pt_resnet50_timm",
                "pt_resnet50",
                "pt_resnext50_torchhub",
                "pt_resnext101_torchhub",
                "pt_resnext14_osmr",
                "pt_resnext26_osmr",
                "pt_resnext101_fb_wsl",
                "pt_resnext101_osmr",
                "pt_resnext50_osmr",
                "pt_retinanet_rn152fpn",
                "pt_retinanet_rn101fpn",
                "pt_retinanet_rn50fpn",
                "pt_unet_qubvel_pt",
                "pt_wide_resnet101_2_timm",
                "pt_wide_resnet50_2_hub",
                "pt_wide_resnet50_2_timm",
                "pt_wide_resnet101_2_hub",
                "pt_xception65_timm",
                "pt_xception71_timm",
                "pt_xception41_timm",
                "pt_xception_timm",
            ]
        },
    ),
    (
        Sqrt0,
        [((48,), torch.float32)],
        {
            "model_name": [
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_ghostnet_100",
                "pt_googlenet",
                "pt_hrnet_timm_hrnet_w48",
                "pt_hrnet_osmr_hrnetv2_w48",
                "pt_mobilenet_v1_192",
                "mobilenetv2_160",
                "mobilenetv2_96",
                "pt_mobilenet_v3_small",
                "pt_mobilenetv3_small_100",
                "pt_yolox_m",
                "pt_yolox_tiny",
            ]
        },
    ),
    (
        Sqrt0,
        [((24,), torch.float32)],
        {
            "model_name": [
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_googlenet",
                "pt_mobilenet_v1_192",
                "mobilenetv2_basic",
                "mobilenetv2_deeplabv3",
                "mobilenetv2_160",
                "mobilenetv2_96",
                "mobilenetv2_timm",
                "mobilenetv2_224",
                "pt_mobilenet_v3_small",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_small_100",
                "pt_mobilenetv3_large_100",
                "pt_yolox_tiny",
            ]
        },
    ),
    (
        Sqrt0,
        [((56,), torch.float32)],
        {
            "model_name": [
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_ghostnet_100",
                "mobilenetv2_96",
            ]
        },
    ),
    (
        Sqrt0,
        [((112,), torch.float32)],
        {
            "model_name": [
                "pt_efficientnet_b4_timm",
                "pt_efficientnet_b4_torchvision",
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_googlenet",
                "mobilenetv2_96",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
                "pt_vovnet27s",
            ]
        },
    ),
    (Sqrt0, [((272,), torch.float32)], {"model_name": ["pt_efficientnet_b4_timm", "pt_efficientnet_b4_torchvision"]}),
    (Sqrt0, [((2688,), torch.float32)], {"model_name": ["pt_efficientnet_b4_timm", "pt_efficientnet_b4_torchvision"]}),
    (
        Sqrt0,
        [((40,), torch.float32)],
        {
            "model_name": [
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w40",
                "pt_mobilenet_v3_small",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_small_100",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (
        Sqrt0,
        [((80,), torch.float32)],
        {
            "model_name": [
                "pt_efficientnet_b0_torchvision",
                "pt_efficientnet_b0_timm",
                "pt_ghostnet_100",
                "pt_hrnet_osmr_hrnetv2_w40",
                "pt_hrnet_timm_hrnet_w40",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_large_100",
                "pt_vovnet27s",
                "pt_yolox_x",
            ]
        },
    ),
    (Sqrt0, [((8,), torch.float32)], {"model_name": ["pt_ghostnet_100", "mobilenetv2_96"]}),
    (Sqrt0, [((12,), torch.float32)], {"model_name": ["pt_ghostnet_100"]}),
    (
        Sqrt0,
        [((36,), torch.float32)],
        {
            "model_name": [
                "pt_ghostnet_100",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_timm_hrnet_w18_small_v2",
            ]
        },
    ),
    (
        Sqrt0,
        [((72,), torch.float32)],
        {
            "model_name": [
                "pt_ghostnet_100",
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_timm_hrnet_w18_small_v2",
                "mobilenetv2_160",
                "pt_mobilenet_v3_small",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_small_100",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (Sqrt0, [((20,), torch.float32)], {"model_name": ["pt_ghostnet_100"]}),
    (
        Sqrt0,
        [((60,), torch.float32)],
        {"model_name": ["pt_ghostnet_100", "pt_hrnet_timm_hrnet_w30", "pt_hrnet_osmr_hrnetv2_w30"]},
    ),
    (
        Sqrt0,
        [((120,), torch.float32)],
        {
            "model_name": [
                "pt_ghostnet_100",
                "pt_hrnet_timm_hrnet_w30",
                "pt_hrnet_osmr_hrnetv2_w30",
                "mobilenetv2_160",
                "pt_mobilenet_v3_small",
                "pt_mobilenet_v3_large",
                "pt_mobilenetv3_small_100",
                "pt_mobilenetv3_large_100",
            ]
        },
    ),
    (Sqrt0, [((100,), torch.float32)], {"model_name": ["pt_ghostnet_100"]}),
    (Sqrt0, [((92,), torch.float32)], {"model_name": ["pt_ghostnet_100"]}),
    (Sqrt0, [((208,), torch.float32)], {"model_name": ["pt_googlenet"]}),
    (
        Sqrt0,
        [((18,), torch.float32)],
        {
            "model_name": [
                "pt_hrnet_timm_hrnet_w18",
                "pt_hrnet_osmr_hrnet_w18_small_v2",
                "pt_hrnet_osmr_hrnetv2_w18",
                "pt_hrnet_timm_hrnet_w18_small_v2",
            ]
        },
    ),
    (Sqrt0, [((30,), torch.float32)], {"model_name": ["pt_hrnet_timm_hrnet_w30", "pt_hrnet_osmr_hrnetv2_w30"]}),
    (Sqrt0, [((44,), torch.float32)], {"model_name": ["pt_hrnet_timm_hrnet_w44", "pt_hrnet_osmr_hrnetv2_w44"]}),
    (
        Sqrt0,
        [((88,), torch.float32)],
        {
            "model_name": [
                "pt_hrnet_timm_hrnet_w44",
                "pt_hrnet_osmr_hrnetv2_w44",
                "pt_mobilenet_v3_small",
                "pt_mobilenetv3_small_100",
            ]
        },
    ),
    (Sqrt0, [((176,), torch.float32)], {"model_name": ["pt_hrnet_timm_hrnet_w44", "pt_hrnet_osmr_hrnetv2_w44"]}),
    (Sqrt0, [((200,), torch.float32)], {"model_name": ["pt_mobilenet_v3_large", "pt_mobilenetv3_large_100"]}),
    (Sqrt0, [((184,), torch.float32)], {"model_name": ["pt_mobilenet_v3_large", "pt_mobilenetv3_large_100"]}),
    (Sqrt0, [((64, 3, 64, 1), torch.float32)], {"model_name": ["pt_swinv2_tiny_patch4_window8_256"]}),
    (Sqrt0, [((16, 6, 64, 1), torch.float32)], {"model_name": ["pt_swinv2_tiny_patch4_window8_256"]}),
    (Sqrt0, [((4, 12, 64, 1), torch.float32)], {"model_name": ["pt_swinv2_tiny_patch4_window8_256"]}),
    (Sqrt0, [((1, 24, 64, 1), torch.float32)], {"model_name": ["pt_swinv2_tiny_patch4_window8_256"]}),
    (
        Sqrt0,
        [((728,), torch.float32)],
        {"model_name": ["pt_xception65_timm", "pt_xception71_timm", "pt_xception41_timm", "pt_xception_timm"]},
    ),
]


@pytest.mark.push
@pytest.mark.parametrize("forge_module_and_shapes_dtypes", forge_modules_and_shapes_dtypes_list, ids=ids_func)
def test_module(forge_module_and_shapes_dtypes, record_property):
    record_property("frontend", "tt-forge-fe")

    forge_module, operand_shapes_dtypes, metadata = forge_module_and_shapes_dtypes

    for metadata_name, metadata_value in metadata.items():
        record_property(metadata_name, metadata_value)

    inputs = [
        Tensor.create_from_shape(operand_shape, operand_dtype) for operand_shape, operand_dtype in operand_shapes_dtypes
    ]

    framework_model = forge_module(forge_module.__name__)
    framework_model.process_framework_parameters()

    compiled_model = compile(framework_model, sample_inputs=inputs)

    verify(inputs, framework_model, compiled_model)
