# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
#
# Register of all detected failing reasons by operator

from test.operators.utils import FailingReasons


class FailingReasonsRegister:

    all = [
        ("add", FailingReasons.DATA_MISMATCH),
        ("clamp", FailingReasons.SPECIAL_VALUES),
        ("clamp", FailingReasons.TTNN_RUNTIME),
        ("concatenate", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("concatenate", FailingReasons.ALLOCATION_FAILED),
        ("conv2d", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("conv2d", FailingReasons.ALLOCATION_FAILED),
        ("conv2d", FailingReasons.COMPILATION_FAILED),
        ("conv2d", FailingReasons.CONV2D_VALIDATE_ARGS),
        ("conv2d", FailingReasons.DATA_MISMATCH),
        ("conv2d", FailingReasons.DTYPE_MISMATCH),
        ("conv2d", FailingReasons.NOT_IMPLEMENTED),
        ("conv2d", FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("conv2d", FailingReasons.UNSUPPORTED_SPECIAL_CASE),
        ("conv2d", FailingReasons.WRONG_SCALAR_TYPE),
        ("conv_transpose_2d", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("conv_transpose_2d", FailingReasons.ALLOCATION_FAILED),
        ("conv_transpose_2d", FailingReasons.DATA_MISMATCH),
        ("conv_transpose_2d", FailingReasons.DTYPE_MISMATCH),
        ("conv_transpose_2d", FailingReasons.MLIR_RUNTIME),
        ("conv_transpose_2d", FailingReasons.TVM_RUNTIME),
        ("conv_transpose_2d", FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("conv_transpose_2d", FailingReasons.WRONG_SCALAR_TYPE),
        ("cos", FailingReasons.DATA_MISMATCH),
        ("cumsum", FailingReasons.DATA_MISMATCH),
        ("div", FailingReasons.DATA_MISMATCH),
        ("div", FailingReasons.DTYPE_MISMATCH),
        ("div", FailingReasons.SPECIAL_VALUES),
        ("embedding", FailingReasons.ALLOCATION_FAILED),
        ("embedding", FailingReasons.COMPILATION_FAILED),
        ("embedding", FailingReasons.DATA_MISMATCH),
        # ("eq", FailingReasons.DTYPE_MISMATCH),  # covered by failing rule
        ("ge", FailingReasons.DTYPE_MISMATCH),
        ("gelu", FailingReasons.DATA_MISMATCH),
        ("gt", FailingReasons.DTYPE_MISMATCH),
        ("layer_norm", FailingReasons.DATA_MISMATCH),
        ("layer_norm", FailingReasons.INTERNAL_TVM_ERROR),
        ("layer_norm", FailingReasons.UNSUPPORTED_DIMENSION),
        ("leaky_relu", FailingReasons.DATA_MISMATCH),
        ("linear", FailingReasons.DATA_MISMATCH),
        ("linear", FailingReasons.MICROBATCHING_UNSUPPORTED),
        ("log", FailingReasons.DATA_MISMATCH),
        ("log1p", FailingReasons.DATA_MISMATCH),
        ("lt", FailingReasons.DTYPE_MISMATCH),
        ("matmul", FailingReasons.DATA_MISMATCH),
        ("matmul", FailingReasons.INTERNAL_TVM_ERROR),
        ("matmul", FailingReasons.TTNN_RUNTIME),
        ("matmul", FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("max", FailingReasons.BUGGY_SHAPE),
        ("max", FailingReasons.DATA_MISMATCH),
        ("max", FailingReasons.FORGE_RUNTIME),
        ("max", FailingReasons.SPECIAL_VALUES),
        ("maximum", FailingReasons.DATA_MISMATCH),
        ("mean", FailingReasons.DATA_MISMATCH),
        ("minimum", FailingReasons.DATA_MISMATCH),
        ("mul", FailingReasons.DATA_MISMATCH),
        ("ne", FailingReasons.DTYPE_MISMATCH),
        ("pow", FailingReasons.DATA_MISMATCH),
        ("pow", FailingReasons.SPECIAL_VALUES),
        ("pow", FailingReasons.UNSUPPORTED_SPECIAL_CASE),
        ("reciprocal", FailingReasons.DATA_MISMATCH),
        ("repeat_interleave", FailingReasons.DATA_MISMATCH),
        ("repeat_interleave", FailingReasons.INFERENCE_FAILED),
        ("reshape", FailingReasons.INTERNAL_TVM_ERROR),
        ("rsqrt", FailingReasons.DATA_MISMATCH),
        ("sin", FailingReasons.DATA_MISMATCH),
        ("softmax", FailingReasons.DATA_MISMATCH),
        # ("softmax", FailingReasons.UNSUPORTED_AXIS),  # covered by failing rule
        ("softmax", FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("sqrt", FailingReasons.DATA_MISMATCH),
        ("square", FailingReasons.ATTRIBUTE_ERROR),
        ("squeeze", FailingReasons.COMPILATION_FAILED),
        ("squeeze", FailingReasons.INTERNAL_TVM_ERROR),
        ("squeeze", FailingReasons.TVM_RUNTIME),
        ("sub", FailingReasons.DATA_MISMATCH),
        ("sum", FailingReasons.DATA_MISMATCH),
        ("transpose", FailingReasons.DATA_MISMATCH),
        ("transpose", FailingReasons.MLIR_RUNTIME),
    ]
