# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
#
# Register of all detected failing reasons by operator

from test.operators.utils import FailingReasons


class FailingReasonsRegister:

    # List of failing reasons for each operator
    # Format: (operator, failing_reason)
    xfail = [
        ("add", FailingReasons.DATA_MISMATCH),
        ("avg_pool_2d", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("avg_pool_2d", FailingReasons.ALLOCATION_FAILED),
        ("avg_pool_2d", FailingReasons.DATA_MISMATCH),
        ("avg_pool_2d", FailingReasons.FORGE_RUNTIME),
        ("avg_pool_2d", FailingReasons.INCORRECT_TENSOR_SHAPE),
        ("clamp", FailingReasons.DTYPE_MISMATCH),
        ("clamp", FailingReasons.FORGE_RUNTIME),
        ("concatenate", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("conv2d", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("conv2d", FailingReasons.ALLOCATION_FAILED),
        ("conv2d", FailingReasons.CONV2D_VALIDATE_ARGS),
        ("conv2d", FailingReasons.DATA_MISMATCH),
        ("conv2d", FailingReasons.NOT_IMPLEMENTED),
        ("conv2d", FailingReasons.UNSUPPORTED_SPECIAL_CASE),
        ("conv_transpose_2d", FailingReasons.ALLOCATION_CIRCULAR_BUFFER),
        ("conv_transpose_2d", FailingReasons.ALLOCATION_FAILED),
        ("conv_transpose_2d", FailingReasons.ASSERT_DIM),
        ("conv_transpose_2d", FailingReasons.ASSERT_GROUPS),
        ("conv_transpose_2d", FailingReasons.ASSERT_STRIDE),
        ("conv_transpose_2d", FailingReasons.DATA_MISMATCH),
        ("conv_transpose_2d", FailingReasons.MLIR_RUNTIME),
        ("conv_transpose_2d", FailingReasons.SPECIAL_VALUES),
        ("cos", FailingReasons.DATA_MISMATCH),
        ("cumsum", FailingReasons.DATA_MISMATCH),
        ("div", FailingReasons.DATA_MISMATCH),
        ("div", FailingReasons.DTYPE_MISMATCH),
        ("div", FailingReasons.SPECIAL_VALUES),
        ("embedding", FailingReasons.ALLOCATION_FAILED),
        ("embedding", FailingReasons.COMPILATION_FAILED),
        ("embedding", FailingReasons.SPECIAL_VALUES),
        ("exp", FailingReasons.DATA_MISMATCH),
        ("ge", FailingReasons.DATA_MISMATCH),
        ("ge", FailingReasons.DTYPE_MISMATCH),
        ("gt", FailingReasons.DATA_MISMATCH),
        ("gt", FailingReasons.DTYPE_MISMATCH),
        ("isnan", FailingReasons.DTYPE_MISMATCH),
        ("layer_norm", FailingReasons.DATA_MISMATCH),
        ("layer_norm", FailingReasons.INTERNAL_TVM_ERROR),
        ("layer_norm", FailingReasons.SPECIAL_VALUES),
        ("layer_norm", FailingReasons.UNSUPPORTED_DIMENSION),
        ("linear", FailingReasons.ALLOCATION_FAILED),
        ("linear", FailingReasons.DATA_MISMATCH),
        ("log", FailingReasons.SPECIAL_VALUES),
        ("log1p", FailingReasons.DATA_MISMATCH),
        ("log1p", FailingReasons.DTYPE_MISMATCH),
        ("log1p", FailingReasons.SPECIAL_VALUES),
        ("lt", FailingReasons.DATA_MISMATCH),
        ("lt", FailingReasons.DTYPE_MISMATCH),
        ("matmul", FailingReasons.DATA_MISMATCH),
        ("matmul", FailingReasons.INTERNAL_TVM_ERROR),
        ("matmul", FailingReasons.TTNN_RUNTIME),
        ("matmul", FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("max", FailingReasons.BUGGY_SHAPE),
        ("max", FailingReasons.FORGE_RUNTIME),
        ("maximum", FailingReasons.DATA_MISMATCH),
        ("mean", FailingReasons.COMPILATION_FAILED),
        ("minimum", FailingReasons.DATA_MISMATCH),
        ("mul", FailingReasons.DATA_MISMATCH),
        ("ne", FailingReasons.DTYPE_MISMATCH),
        ("neg", FailingReasons.DTYPE_MISMATCH),
        ("pow", FailingReasons.DATA_MISMATCH),
        ("pow", FailingReasons.SPECIAL_VALUES),
        ("pow", FailingReasons.UNSUPPORTED_SPECIAL_CASE),
        ("reciprocal", FailingReasons.DATA_MISMATCH),
        ("reciprocal", FailingReasons.SPECIAL_VALUES),
        ("remainder", FailingReasons.DATA_MISMATCH),
        ("remainder", FailingReasons.SPECIAL_VALUES),
        ("repeat_interleave", FailingReasons.DATA_MISMATCH),
        ("repeat_interleave", FailingReasons.INFERENCE_FAILED),
        ("repeat_interleave", FailingReasons.SPECIAL_VALUES),
        ("reshape", FailingReasons.INTERNAL_TVM_ERROR),
        ("rsqrt", FailingReasons.SPECIAL_VALUES),
        ("sin", FailingReasons.DATA_MISMATCH),
        ("softmax", FailingReasons.DATA_MISMATCH),
        ("softmax", FailingReasons.SPECIAL_VALUES),
        ("softmax", FailingReasons.UNSUPPORTED_AXIS),
        ("sqrt", FailingReasons.SPECIAL_VALUES),
        ("squeeze", FailingReasons.COMPILATION_FAILED),
        ("squeeze", FailingReasons.INTERNAL_TVM_ERROR),
        ("sub", FailingReasons.DATA_MISMATCH),
        ("sub", FailingReasons.DTYPE_MISMATCH),
        ("sum", FailingReasons.DATA_MISMATCH),
        ("sum", FailingReasons.NOT_IMPLEMENTED),
        ("tanh", FailingReasons.DATA_MISMATCH),
        ("where", FailingReasons.DATA_MISMATCH),
    ]

    # List of skip reasons for each operator
    # Format: (operator, skip_reason, failing_reason)
    skip = [
        ("matmul", FailingReasons.HIGH_MEMORY, None),
        ("conv2d", FailingReasons.FATAL_ERROR, None),
        ("conv_transpose_2d", FailingReasons.FATAL_ERROR, FailingReasons.ASSERT_STRIDE),
        ("conv_transpose_2d", FailingReasons.FATAL_ERROR, FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("embedding", FailingReasons.FATAL_ERROR, None),
        ("layer_norm", FailingReasons.FATAL_ERROR, None),
        ("linear", FailingReasons.FATAL_ERROR, None),
        ("pow", FailingReasons.FATAL_ERROR, None),
        ("square", FailingReasons.FATAL_ERROR, None),
        ("avg_pool_2d", FailingReasons.INFERENCE_FROZE, None),
    ]
