# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
#
# Register of all detected failing reasons by operator

from test.operators.utils import FailingReasons


class FailingReasonsRegister:

    # List of failing reasons for each operator
    # Format: (operator, failing_reason)
    xfail = [
        ("add", FailingReasons.DATA_MISMATCH),
        ("clamp", FailingReasons.FORGE_RUNTIME),
        ("clamp", FailingReasons.MLIR_NOT_VERIFIED),
        ("concatenate", FailingReasons.CIRCULAR_BUFFER_EXCEEDS_L1),
        ("conv2d", FailingReasons.ALLOCATION_FAILED),
        ("conv2d", FailingReasons.CIRCULAR_BUFFER_CLASH),
        ("conv2d", FailingReasons.CIRCULAR_BUFFER_EXCEEDS_L1),
        ("conv2d", FailingReasons.CIRCULAR_MODE_NOT_SUPPORTED),
        ("conv2d", FailingReasons.CONV2D_VALIDATE_ARGS),
        ("conv2d", FailingReasons.DATA_MISMATCH),
        ("conv2d", FailingReasons.NOT_IMPLEMENTED_ATEN),
        ("conv2d", FailingReasons.WEIGHT_BIAS_SHAPE_MISMATCH),
        ("conv_transpose_2d", FailingReasons.ALLOCATION_FAILED),
        ("conv_transpose_2d", FailingReasons.ASSERT_DIM),
        ("conv_transpose_2d", FailingReasons.ASSERT_GROUPS),
        ("conv_transpose_2d", FailingReasons.ASSERT_STRIDE),
        ("conv_transpose_2d", FailingReasons.CIRCULAR_BUFFER_CLASH),
        ("conv_transpose_2d", FailingReasons.DATA_MISMATCH),
        ("conv_transpose_2d", FailingReasons.MLIR_RUNTIME),
        ("conv_transpose_2d", FailingReasons.VERIFICATION_FAILED_PCC_NAN),
        ("cos", FailingReasons.DATA_MISMATCH),
        ("cumsum", FailingReasons.DATA_MISMATCH),
        ("div", FailingReasons.DATA_MISMATCH),
        ("div", FailingReasons.DTYPE_MISMATCH),
        ("div", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("embedding", FailingReasons.ALLOCATION_FAILED),
        ("embedding", FailingReasons.MLIR_NOT_VERIFIED),
        ("embedding", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("exp", FailingReasons.DATA_MISMATCH),
        ("ge", FailingReasons.DATA_MISMATCH),
        ("ge", FailingReasons.DTYPE_MISMATCH),
        ("gt", FailingReasons.DATA_MISMATCH),
        ("gt", FailingReasons.DTYPE_MISMATCH),
        ("isnan", FailingReasons.DTYPE_MISMATCH),
        ("layer_norm", FailingReasons.DATA_MISMATCH),
        ("layer_norm", FailingReasons.UNHANDLED_CASE_NONE),
        ("layer_norm", FailingReasons.UNSUPPORTED_DIMENSION),
        ("layer_norm", FailingReasons.VERIFICATION_FAILED_PCC_NAN),
        ("linear", FailingReasons.ALLOCATION_FAILED),
        ("linear", FailingReasons.DATA_MISMATCH),
        ("log", FailingReasons.DATA_MISMATCH),
        ("log", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("log1p", FailingReasons.DATA_MISMATCH),
        ("log1p", FailingReasons.DTYPE_MISMATCH),
        ("log1p", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("lt", FailingReasons.DATA_MISMATCH),
        ("lt", FailingReasons.DTYPE_MISMATCH),
        ("matmul", FailingReasons.DATA_MISMATCH),
        ("matmul", FailingReasons.RELAY_OP_SHAPE_CHECK),
        ("matmul", FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("matmul", FailingReasons.UNSUPPORTED_INPUT_SHAPE_MATMUL),
        ("maximum", FailingReasons.DATA_MISMATCH),
        ("mean", FailingReasons.MLIR_NOT_VERIFIED),
        ("minimum", FailingReasons.DATA_MISMATCH),
        ("mul", FailingReasons.DATA_MISMATCH),
        ("ne", FailingReasons.DTYPE_MISMATCH),
        ("neg", FailingReasons.DTYPE_MISMATCH),
        ("pow", FailingReasons.DATA_MISMATCH),
        ("pow", FailingReasons.UNSUPPORTED_EXPONENT_VALUE),
        ("pow", FailingReasons.VERIFICATION_FAILED_PCC_NAN),
        ("pow", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("reciprocal", FailingReasons.DATA_MISMATCH),
        ("reciprocal", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("remainder", FailingReasons.DATA_MISMATCH),
        ("remainder", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("repeat_interleave", FailingReasons.DATA_MISMATCH),
        ("repeat_interleave", FailingReasons.INFERENCE_FAILED),
        ("repeat_interleave", FailingReasons.VERIFICATION_FAILED_PCC_NAN),
        ("reshape", FailingReasons.TENSOR_TRANSFORM_SHAPE_CHECK),
        ("rsqrt", FailingReasons.DATA_MISMATCH),
        ("rsqrt", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("sin", FailingReasons.DATA_MISMATCH),
        ("softmax", FailingReasons.DATA_MISMATCH),
        ("softmax", FailingReasons.UNSUPPORTED_AXIS),
        ("softmax", FailingReasons.VERIFICATION_FAILED_PCC_NAN),
        ("sqrt", FailingReasons.VERIFICATION_FAILED_SPECIAL_VALUES),
        ("square", FailingReasons.ATTRIBUTE_ERROR),
        ("squeeze", FailingReasons.CANNOT_SQUEEZE_AXIS_NOT_ONE),
        ("squeeze", FailingReasons.MLIR_NOT_VERIFIED),
        ("sub", FailingReasons.DATA_MISMATCH),
        ("sub", FailingReasons.DTYPE_MISMATCH),
        ("sum", FailingReasons.DATA_MISMATCH),
        ("sum", FailingReasons.NOT_IMPLEMENTED),
        ("tanh", FailingReasons.DATA_MISMATCH),
    ]

    # List of skip reasons for each operator
    # Format: (operator, skip_reason, failing_reason)
    skip = [
        ("matmul", FailingReasons.HIGH_MEMORY, None),
        ("conv2d", FailingReasons.FATAL_ERROR, None),
        ("conv_transpose_2d", FailingReasons.FATAL_ERROR, FailingReasons.ASSERT_STRIDE),
        ("conv_transpose_2d", FailingReasons.FATAL_ERROR, FailingReasons.UNSUPPORTED_DATA_FORMAT),
        ("embedding", FailingReasons.FATAL_ERROR, None),
        ("layer_norm", FailingReasons.FATAL_ERROR, None),
        ("linear", FailingReasons.FATAL_ERROR, None),
        ("pow", FailingReasons.FATAL_ERROR, None),
        ("square", FailingReasons.FATAL_ERROR, None),
    ]
