#!/usr/bin/env bash

# NOTE
# These env variables are stored in this file because they are needed by both
# toolchain project and the pybuda project. This file is sourced by both projects.
# For tt-mlir we have similar env variables but since we build toolchain and binaries of tt-mlir
# using install.sh from tt-mlir project, we only define them in pybuda project top level cmake file.

# Set PYBUDA_TOOLCHAIN_DIR to a default value if not already set
export PYBUDA_TOOLCHAIN_DIR="${PYBUDA_TOOLCHAIN_DIR:-/opt/pybuda-toolchain}"

# Set PYTHON_VERSION
if [[ "$(uname)" == "Linux" ]]; then
export PYBUDA_PYTHON_VERSION="${PYBUDA_PYTHON_VERSION:-python3.10}"
elif [[ "$(uname)" == "Darwin" ]]; then
export PYBUDA_PYTHON_VERSION="${PYBUDA_PYTHON_VERSION:-/usr/bin/python3}"
else
echo "Error: Unsupported OS $(uname)"
fi

# Set PYBUDA_VENV_DIR to a default value if not already set
export PYBUDA_VENV_DIR="${PYBUDA_VENV_DIR:-${PYBUDA_TOOLCHAIN_DIR}/venv}"

[ -f $PYBUDA_VENV_DIR/bin/activate ] && source $PYBUDA_VENV_DIR/bin/activate

if [ -n "$PROJECT_ROOT" ]; then
    export TT_METAL_HOME="$PROJECT_ROOT/third_party/tt-mlir/third_party/tt-metal/src/tt-metal"
else
    export TT_METAL_HOME="$(pwd)/third_party/tt-mlir/third_party/tt-metal/src/tt-metal"
fi

export TTMLIR_TOOLCHAIN_DIR="${TTMLIR_TOOLCHAIN_DIR:-/opt/ttmlir-toolchain}"

export TTMLIR_VENV_DIR="${TTMLIR_VENV_DIR:-${TTMLIR_TOOLCHAIN_DIR}/venv}"

export TTMLIR_ENV_ACTIVATED=1

export ARCH_NAME="${ARCH_NAME:-wormhole_b0}"
