#!/usr/bin/env bash

# NOTE
# These env variables are stored in this file because they are needed by both
# toolchain project and the tt-forge project. This file is sourced by both projects.
# For tt-mlir we have similar env variables but since we build toolchain and binaries of tt-mlir
# using install.sh from tt-mlir project, we only define them in tt-forge project top level cmake file.

# Set TTFORGE_TOOLCHAIN_DIR to a default value if not already set
export TTFORGE_TOOLCHAIN_DIR="${TTFORGE_TOOLCHAIN_DIR:-/opt/ttforge-toolchain}"

# Set PYTHON_VERSION
export TTFORGE_PYTHON_VERSION="${TTFORGE_PYTHON_VERSION:-python3.10}"

# Set TTFORGE_VENV_DIR to a default value if not already set
export TTFORGE_VENV_DIR="${TTFORGE_VENV_DIR:-${TTFORGE_TOOLCHAIN_DIR}/venv}"

[ -f $TTFORGE_VENV_DIR/bin/activate ] && source $TTFORGE_VENV_DIR/bin/activate

export TTMLIR_TOOLCHAIN_DIR="${TTMLIR_TOOLCHAIN_DIR:-/opt/ttmlir-toolchain}"

export TTMLIR_VENV_DIR="${TTMLIR_VENV_DIR:-${TTMLIR_TOOLCHAIN_DIR}/venv}"

export TTMLIR_ENV_ACTIVATED=1

export ARCH_NAME="${ARCH_NAME:-wormhole_b0}"

# This one is needed so that when building `tt-mlir` from `tt-forge` project, the `tt-mlir` project can
# find the flatbuffer compiler binary (`flatc`) in the toolchain directory.
export PATH="$TTMLIR_TOOLCHAIN_DIR/bin:$PATH"
