name: Cleanup Runner

on:
  workflow_dispatch:
    inputs:
      runner_name:
        description: 'Select the self-hosted runner to clean'
        required: true
        default: 'n150'
      purge_docker:
        description: 'Purge docker images'
        required: true
        default: 'true'
        type: boolean
      delete_workspace:
        description: 'Delete the workspace'
        required: true
        default: 'false'
        type: boolean

jobs:
  cleanup:
    runs-on: ${{ github.event.inputs.runner_name }}
    
    steps:
      - name: Report free space before cleanup
        run: |
          echo "Free space before cleanup:"
          df -h

      - name: Purge all Docker cached images
        if: ${{ github.event.inputs.purge_docker }}
        run: |
          echo "Removing all unused Docker images..."
          docker system prune -fa
          echo "Docker images purged."

      - name: Delete work folder
        if: ${{ github.event.inputs.delete_workspace }}
        run: |
          export WORKPLACE=/home/ubuntu/actions-runner/_work
          echo "Deleting work folder $WORKPLACE"
          sudo rm -rf $WORKPLACE
          mkdir -p $GITHUB_WORKSPACE

      - name: Report free space after cleanup
        run: |
          echo "Free space after cleanup:"
          df -h