name: Model Analysis Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 5' # 11:00 PM UTC Friday (12:00 AM Saturday Serbia)

jobs:
  model-analysis-weekly:
    uses: ./.github/workflows/model-analysis.yml
    secrets: inherit
    with:
      generate_models_ops_test: false
