name: On Nightly Models Ops

on:
  workflow_dispatch:
  # Temporarily disabled the scheduled run configuration because there are currently no tests
  # marked with 'nightly_models_ops' in main branch. When model ops tests are added, uncomment the schedule below to
  # automatically run them at 02:00 AM UTC every day.
  # schedule:
  #   - cron: '0 2 * * *'  # Runs at 02:00 AM UTC every day

jobs:
  docker-build:
      uses: ./.github/workflows/build-image.yml
      secrets: inherit
  build:
    needs: docker-build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
  test:
    needs:
      - docker-build
      - build
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test_mark: 'nightly_models_ops'
      test_group_cnt: 4
      test_group_ids: '[1,2,3,4]'
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      runs-on: '[{"runs-on": "n150"}]'
