name: On Nightly Sweeps Tests

on:
  push:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Runs on'
        required: true
        type: choice
        options:
          - n150
          - n300
        default: n150
      operators:
        description: 'Operators to test (comma separated)'
        type: string
        required: false
  schedule:
    - cron: '0 4 * * *'  # Runs at 04:00 UTC every day

# env:
#   RUNS_ON_DEFAULT: n150

jobs:
  # docker-build:
  #     uses: ./.github/workflows/build-image.yml
  #     secrets: inherit
  # build:
  #   needs: docker-build
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit
  #   with:
  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
  test:

    # needs:
    #   - docker-build
    #   - build
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test_mark: 'nightly_sweeps'
      test_group_cnt: 4
      test_group_ids: '[1,2,3,4]'
      # docker-image: ${{ needs.docker-build.outputs.docker-image }}
      docker-image: 'public.ecr.aws/ubuntu/ubuntu:22.04'
      runs-on: '[{"runs-on": "${{ inputs.runs-on || inputs.runs-on.default }}"}]'
      operators: ${{ github.event.inputs.operators }}
