name: On Nightly Sweeps Tests

on:
  push:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Runs on'
        required: true
        type: choice
        options:
          - n150
          - n300
        default: n150
      operators:
        description: 'Operators to test (comma separated)'
        type: string
        required: false
  schedule:
    - cron: '0 4 * * *'  # Runs at 04:00 UTC every day

# env:
#   RUNS_ON_DEFAULT: n150

jobs:

  set_defaults:
    runs-on: ubuntu-latest
    outputs:
      runs_on: ${{ steps.defaults.outputs.runs_on }}
    steps:
      - name: Set defaults
        id: defaults
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "runs_on=$(echo '{\"runs-on\": \"n150\"}' | jq -c .)" >> "$GITHUB_OUTPUT"
          else
            echo "runs_on=$(echo '{\"runs-on\": \"${{ inputs.runs-on }}\"}' | jq -c .)" >> "$GITHUB_OUTPUT"
          fi

  # docker-build:
  #     uses: ./.github/workflows/build-image.yml
  #     secrets: inherit
  # build:
  #   needs: docker-build
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit
  #   with:
  #     docker-image: ${{ needs.docker-build.outputs.docker-image }}
  test:

    needs:
      - set_defaults
    #   - docker-build
    #   - build
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test_mark: 'nightly_sweeps'
      test_group_cnt: 4
      test_group_ids: '[1,2,3,4]'
      # docker-image: ${{ needs.docker-build.outputs.docker-image }}
      docker-image: 'public.ecr.aws/ubuntu/ubuntu:22.04'
      runs-on: ${{ needs.set_defaults.outputs.runs_on }}
      operators: ${{ inputs.operators }}
