name: On nightly xfail

on:
  push:
  workflow_dispatch:
    inputs:
        run_id:
            description: 'Run id'
            required: true
            type: number
  workflow_run:
    workflows:
      - "On nightly"
    types:
      - completed

jobs:
  docker-build:
      uses: ./.github/workflows/build-image.yml
      secrets: inherit
  test_full_model_xpassing:
    needs:
      - docker-build
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test_mark: 'nightly and xfail'
      test_group_cnt: 4
      test_group_ids: '[1,2,3,4]'
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      runs-on: '[{"runs-on": "n150"}]'
      run-id: ${{ github.event.workflow_run.id || github.event.inputs.run_id }}
