name: Perf only

on:
  workflow_dispatch:
  push:

jobs:
  docker-build:
      uses: ./.github/workflows/build-image.yml
      secrets: inherit

  build:
    needs: docker-build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}

  perf-benchmark:
    needs:
      - docker-build
      - build
    uses: ./.github/workflows/perf-benchmark.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
