name: Sweeps Tests

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Runs on'
        required: true
        type: string
        default: n150
      operators:
        description: 'Operators to test (comma separated)'
        type: string
        required: false

jobs:
  docker-build:
      uses: ./.github/workflows/build-image.yml
      secrets: inherit
  build:
    needs: docker-build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
  test:
    needs:
      - docker-build
      - build
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test_mark: 'nightly_sweeps'
      test_group_cnt: 4
      test_group_ids: '[1,2,3,4]'
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      runs-on: '[{"runs-on": "${{ github.event.inputs.runs-on }}"}]'
      operators: ${{ github.event.inputs.operators }}
